#!/usr/bin/env python3
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source" / "rules.yaml"
HEADER = "# AUTO-GENERATED by scripts/build.py. Edit source/rules.yaml instead.\n"


def load_source():
    with SOURCE.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def norm_rule(item):
    if isinstance(item, str):
        parts = [p.strip() for p in item.split(",")]
        if len(parts) < 2:
            raise ValueError(f"Invalid rule string: {item}")
        return {
            "type": parts[0],
            "value": parts[1],
            "options": ",".join(parts[2:]) if len(parts) > 2 else "",
            "comment": "",
        }
    if isinstance(item, dict):
        return {
            "type": str(item["type"]).strip(),
            "value": str(item["value"]).strip(),
            "options": str(item.get("options", "")).strip(),
            "comment": str(item.get("comment", "")).strip(),
        }
    raise TypeError(f"Unsupported rule item: {item!r}")


def iter_categories(data):
    for key, cat in data.get("categories", {}).items():
        yield key, cat, [norm_rule(x) for x in cat.get("rules", [])]


def rule_line(rule, policy=None, include_policy=True, stash_payload=False):
    parts = [rule["type"], rule["value"]]
    if include_policy and policy:
        parts.append(policy)
    if rule["options"]:
        parts.extend([p for p in rule["options"].split(",") if p])
    line = ",".join(parts)
    if stash_payload:
        return f"  - {line}"
    return line


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def build_qx(data):
    lines = [HEADER.rstrip(), "# Quantumult X 分流规则", ""]
    for key, cat, rules in iter_categories(data):
        lines.append(f"# {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"# {r['comment']}")
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    lines.append("# Final")
    lines.extend(data.get("final", {}).get("qx", []))
    write(ROOT / "quantumult-x" / "rules.list", "\n".join(lines).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Quantumult X - {cat.get('name', key)}", ""]
        for r in rules:
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        write(ROOT / "quantumult-x" / "rules" / f"{key}.list", "\n".join(lines).rstrip() + "\n")


def build_loon(data):
    lines = [HEADER.rstrip(), "# Loon 分流规则", ""]
    for key, cat, rules in iter_categories(data):
        lines.append(f"# {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"# {r['comment']}")
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    lines.append("# Final")
    lines.extend(data.get("final", {}).get("loon", []))
    write(ROOT / "loon" / "rules.list", "\n".join(lines).rstrip() + "\n")

    plugin = [
        "#!name=Eggy Proxy Rules",
        "#!desc=个人代理规则插件：由 source/rules.yaml 自动生成",
        "#!author=liueggy",
        "#!homepage=https://github.com/liueggy/proxy-rules",
        "#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png",
        "",
        "[Rule]",
    ]
    for key, cat, rules in iter_categories(data):
        plugin.append(f"# {cat.get('name', key)}")
        for r in rules:
            plugin.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        plugin.append("")
    plugin.extend(data.get("final", {}).get("loon", []))
    plugin.extend(["", "[Rewrite]", "# ^https?:\\/\\/example\\.com\\/ads reject", "", "[MITM]", "# hostname = example.com"])
    write(ROOT / "loon" / "plugin.plugin", "\n".join(plugin).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Loon - {cat.get('name', key)}", ""]
        for r in rules:
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        write(ROOT / "loon" / "rules" / f"{key}.list", "\n".join(lines).rstrip() + "\n")


def build_stash(data):
    lines = [HEADER.rstrip(), "# Stash / Clash / Mihomo override", "", "name: Proxy Rules Override", "", "rules:"]
    for key, cat, rules in iter_categories(data):
        lines.append(f"  # {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"  # {r['comment']}")
            lines.append("  - " + rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    for final in data.get("final", {}).get("stash", []):
        lines.append(f"  - {final}")
    write(ROOT / "stash" / "override.yaml", "\n".join(lines).rstrip() + "\n")

    payload_all = [HEADER.rstrip(), "# Stash / Clash / Mihomo classical ruleset", "payload:"]
    for key, cat, rules in iter_categories(data):
        payload_all.append(f"  # {cat.get('name', key)}")
        for r in rules:
            payload_all.append(rule_line(r, include_policy=False, stash_payload=True))
        payload_all.append("")
    write(ROOT / "stash" / "rules.yaml", "\n".join(payload_all).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Stash / Clash / Mihomo - {cat.get('name', key)}", "payload:"]
        for r in rules:
            lines.append(rule_line(r, include_policy=False, stash_payload=True))
        write(ROOT / "stash" / "rules" / f"{key}.yaml", "\n".join(lines).rstrip() + "\n")


def iter_external_items(data):
    for provider_key, provider in data.get("external_sources", {}).items():
        base = provider.get("base", {})
        for item_key, item in provider.get("items", {}).items():
            name = item["name"]
            policy = item.get("policy", data["meta"].get("default_policy", "Proxy"))
            yield provider_key, provider, item_key, item, name, policy, base


def build_external(data):
    interval = data.get("meta", {}).get("update_interval", 86400)
    owner = data.get("meta", {}).get("owner", "liueggy")
    repo = data.get("meta", {}).get("repo", "proxy-rules")
    raw_base = f"https://raw.githubusercontent.com/{owner}/{repo}/main"

    qx = [
        "# AUTO-GENERATED by scripts/build.py. Edit source/rules.yaml instead.",
        "# Quantumult X 外部开源规则源",
        "# 用法：复制到 Quantumult X 配置的 [filter_remote] 区域",
        "",
        f"{raw_base}/quantumult-x/rules/direct-servers.list, tag=Eggy Direct Servers, update-interval={interval}, opt-parser=false, enabled=true",
        "",
    ]
    loon = [
        "# AUTO-GENERATED by scripts/build.py. Edit source/rules.yaml instead.",
        "# Loon 外部开源规则源",
        "# 用法：复制到 Loon 配置的 [Remote Rule] 区域",
        "",
        f"{raw_base}/loon/rules/direct-servers.list, policy=DIRECT, tag=Eggy Direct Servers, enabled=true",
        "",
    ]
    stash = [
        "# AUTO-GENERATED by scripts/build.py. Edit source/rules.yaml instead.",
        "# Stash Override：外部开源规则源",
        "# 用法：Stash → Override → 添加远程覆写",
        "",
        "name: External Rule Providers",
        "",
        "rule-providers:",
        "  eggy-custom:",
        "    type: http",
        "    behavior: classical",
        f"    url: {raw_base}/stash/rules/direct-servers.yaml",
        "    path: ./ruleset/eggy/direct-servers.yaml",
        f"    interval: {interval}",
    ]
    stash_rules = [
        "rules:",
        "  # 自己维护的直连规则优先级最高",
        "  - RULE-SET,eggy-custom,DIRECT",
        "",
    ]
    docs = [
        "# 外部开源规则源",
        "",
        "本文件由 `source/rules.yaml` 自动生成。通用大规则建议通过外部远程规则源引用，避免重复维护。",
        "",
        "## 已接入来源",
        "",
    ]
    grouped = {}
    for provider_key, provider, item_key, item, name, policy, base in iter_external_items(data):
        grouped.setdefault(provider_key, provider)
        qx_url = f"{base['qx']}/{name}/{name}.list"
        loon_url = f"{base['loon']}/{name}/{name}.list"
        stash_url = f"{base['stash']}/{name}/{name}.yaml"
        qx.append(f"{qx_url}, tag={name}, force-policy={policy}, update-interval={interval}, opt-parser=false, enabled=true")
        loon.append(f"{loon_url}, policy={policy}, tag={name}, enabled=true")
        provider_name = provider_key.replace('-', '_')
        rule_name = f"{provider_name}-{item_key}".replace("_", "-")
        stash.extend([
            f"  {rule_name}:",
            "    type: http",
            "    behavior: classical",
            f"    url: {stash_url}",
            f"    path: ./ruleset/{provider_name}/{item_key}.yaml",
            f"    interval: {interval}",
        ])
        stash_rules.append(f"  - RULE-SET,{rule_name},{policy}")

    stash.extend(["", *stash_rules, "", "  - GEOIP,CN,DIRECT", "  - MATCH,Proxy"])
    write(ROOT / "quantumult-x" / "external-filter-remote.conf", "\n".join(qx).rstrip() + "\n")
    write(ROOT / "loon" / "external-remote-rules.conf", "\n".join(loon).rstrip() + "\n")
    write(ROOT / "stash" / "external-providers.yaml", "\n".join(stash).rstrip() + "\n")

    policies = sorted({policy for *_rest, policy, _base in iter_external_items(data)} | {"Proxy", "DIRECT"})
    qx_policy = ["# Quantumult X 策略组模板", "# 用法：根据你的节点名称调整后，复制到 [policy] 区域", ""]
    qx_policy.append("static=Proxy, server-tag-regex=.*, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png")
    for p in policies:
        if p in {"Proxy", "DIRECT", "REJECT"}:
            continue
        default = "DIRECT, Proxy" if p == "Apple" else "Proxy, DIRECT"
        qx_policy.append(f"static={p}, {default}")
    write(ROOT / "quantumult-x" / "policy-snippet.conf", "\n".join(qx_policy).rstrip() + "\n")

    loon_policy = ["# Loon 策略组模板", "# 用法：根据你的节点名称调整后，复制到 [Proxy Group] 区域", ""]
    loon_policy.append("Proxy = select, policy-path=你的订阅链接, icon-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png")
    for p in policies:
        if p in {"Proxy", "DIRECT", "REJECT"}:
            continue
        default = "DIRECT, Proxy" if p == "Apple" else "Proxy, DIRECT"
        loon_policy.append(f"{p} = select, {default}")
    write(ROOT / "loon" / "policy-snippet.conf", "\n".join(loon_policy).rstrip() + "\n")

    for provider_key, provider in grouped.items():
        docs.extend([
            f"### {provider.get('name', provider_key)}",
            "",
            f"- GitHub: {provider.get('homepage', '')}",
            f"- Branch: `{provider.get('branch', 'master')}`",
            "",
        ])
    docs.extend([
        "## 已接入分类",
        "",
        "| 来源 | 分类 | 策略 |",
        "|---|---|---|",
    ])
    for provider_key, provider, item_key, item, name, policy, base in iter_external_items(data):
        docs.append(f"| {provider_key} | {name} | `{policy}` |")
    docs.extend([
        "",
        "## 注意",
        "",
        "1. 外部规则会随上游变化，若上游路径调整，远程导入可能失效。",
        "2. 广告拦截规则不要过度叠加，容易导致 App 白屏或登录异常。",
        "3. AI / Streaming 策略组需要你在客户端配置中存在，否则导入规则可能报策略不存在。",
    ])
    write(ROOT / "docs" / "external-sources.md", "\n".join(docs).rstrip() + "\n")


def validate(data):
    seen = set()
    for key, cat, rules in iter_categories(data):
        if not cat.get("policy"):
            raise ValueError(f"Category {key} missing policy")
        for r in rules:
            sig = (r["type"], r["value"], r["options"], cat.get("policy"))
            if sig in seen:
                raise ValueError(f"Duplicate rule: {sig}")
            seen.add(sig)


def main():
    data = load_source()
    validate(data)
    build_qx(data)
    build_loon(data)
    build_stash(data)
    build_external(data)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"build failed: {e}", file=sys.stderr)
        sys.exit(1)
