#!/usr/bin/env python3
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source" / "rules.yaml"
HEADER = "# AUTO-GENERATED by scripts/build.py. Edit source/rules.yaml instead.\n"


def load_source():
    with SOURCE.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def norm_rule(item):
    if isinstance(item, str):
        parts = [p.strip() for p in item.split(",")]
        if len(parts) < 2:
            raise ValueError(f"Invalid rule string: {item}")
        return {
            "type": parts[0],
            "value": parts[1],
            "options": ",".join(parts[2:]) if len(parts) > 2 else "",
            "comment": "",
        }
    if isinstance(item, dict):
        return {
            "type": str(item["type"]).strip(),
            "value": str(item["value"]).strip(),
            "options": str(item.get("options", "")).strip(),
            "comment": str(item.get("comment", "")).strip(),
        }
    raise TypeError(f"Unsupported rule item: {item!r}")


def iter_categories(data):
    for key, cat in data.get("categories", {}).items():
        yield key, cat, [norm_rule(x) for x in cat.get("rules", [])]


def rule_line(rule, policy=None, include_policy=True, stash_payload=False):
    parts = [rule["type"], rule["value"]]
    if include_policy and policy:
        parts.append(policy)
    if rule["options"]:
        parts.extend([p for p in rule["options"].split(",") if p])
    line = ",".join(parts)
    if stash_payload:
        return f"  - {line}"
    return line


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def build_qx(data):
    lines = [HEADER.rstrip(), "# Quantumult X 分流规则", ""]
    for key, cat, rules in iter_categories(data):
        lines.append(f"# {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"# {r['comment']}")
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    lines.append("# Final")
    lines.extend(data.get("final", {}).get("qx", []))
    write(ROOT / "quantumult-x" / "rules.list", "\n".join(lines).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Quantumult X - {cat.get('name', key)}", ""]
        for r in rules:
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        write(ROOT / "quantumult-x" / "rules" / f"{key}.list", "\n".join(lines).rstrip() + "\n")


def build_loon(data):
    lines = [HEADER.rstrip(), "# Loon 分流规则", ""]
    for key, cat, rules in iter_categories(data):
        lines.append(f"# {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"# {r['comment']}")
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    lines.append("# Final")
    lines.extend(data.get("final", {}).get("loon", []))
    write(ROOT / "loon" / "rules.list", "\n".join(lines).rstrip() + "\n")

    plugin = [
        "#!name=Eggy Proxy Rules",
        "#!desc=个人代理规则插件：由 source/rules.yaml 自动生成",
        "#!author=liueggy",
        "#!homepage=https://github.com/liueggy/proxy-rules",
        "#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png",
        "",
        "[Rule]",
    ]
    for key, cat, rules in iter_categories(data):
        plugin.append(f"# {cat.get('name', key)}")
        for r in rules:
            plugin.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        plugin.append("")
    plugin.extend(data.get("final", {}).get("loon", []))
    plugin.extend(["", "[Rewrite]", "# ^https?:\\/\\/example\\.com\\/ads reject", "", "[MITM]", "# hostname = example.com"])
    write(ROOT / "loon" / "plugin.plugin", "\n".join(plugin).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Loon - {cat.get('name', key)}", ""]
        for r in rules:
            lines.append(rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        write(ROOT / "loon" / "rules" / f"{key}.list", "\n".join(lines).rstrip() + "\n")


def build_stash(data):
    lines = [HEADER.rstrip(), "# Stash / Clash / Mihomo override", "", "name: Proxy Rules Override", "", "rules:"]
    for key, cat, rules in iter_categories(data):
        lines.append(f"  # {cat.get('name', key)}")
        for r in rules:
            if r["comment"]:
                lines.append(f"  # {r['comment']}")
            lines.append("  - " + rule_line(r, cat.get("policy", data["meta"].get("default_policy", "Proxy"))))
        lines.append("")
    for final in data.get("final", {}).get("stash", []):
        lines.append(f"  - {final}")
    write(ROOT / "stash" / "override.yaml", "\n".join(lines).rstrip() + "\n")

    payload_all = [HEADER.rstrip(), "# Stash / Clash / Mihomo classical ruleset", "payload:"]
    for key, cat, rules in iter_categories(data):
        payload_all.append(f"  # {cat.get('name', key)}")
        for r in rules:
            payload_all.append(rule_line(r, include_policy=False, stash_payload=True))
        payload_all.append("")
    write(ROOT / "stash" / "rules.yaml", "\n".join(payload_all).rstrip() + "\n")

    for key, cat, rules in iter_categories(data):
        lines = [HEADER.rstrip(), f"# Stash / Clash / Mihomo - {cat.get('name', key)}", "payload:"]
        for r in rules:
            lines.append(rule_line(r, include_policy=False, stash_payload=True))
        write(ROOT / "stash" / "rules" / f"{key}.yaml", "\n".join(lines).rstrip() + "\n")


def validate(data):
    seen = set()
    for key, cat, rules in iter_categories(data):
        if not cat.get("policy"):
            raise ValueError(f"Category {key} missing policy")
        for r in rules:
            sig = (r["type"], r["value"], r["options"], cat.get("policy"))
            if sig in seen:
                raise ValueError(f"Duplicate rule: {sig}")
            seen.add(sig)


def main():
    data = load_source()
    validate(data)
    build_qx(data)
    build_loon(data)
    build_stash(data)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"build failed: {e}", file=sys.stderr)
        sys.exit(1)
